/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Aggregate chain step results into markdown */
export declare function aggregateChainResults(chainType: string, results: Array<string>): string

/** Create a chain execution plan */
export declare function createChainPlan(chainType: string, query: string): NapiChainPlan

export interface NapiAnnexInfo {
  annexType: string
  number: number
  subNumber?: number
  title: string
  rawContent: string
  markdown: string
}

export interface NapiChainPlan {
  chainType: string
  description: string
  steps: Array<NapiChainStep>
  executableGroups: Array<Array<number>>
}

export interface NapiChainStep {
  toolName: string
  params: string
  dependsOn: Array<number>
  parallelGroup?: number
}

export interface NapiDateResult {
  date: string
  endDate?: string
  format: string
  confidence: number
}

export interface NapiHwpResult {
  text: string
  tables: Array<NapiTableData>
}

export interface NapiTableData {
  rows: number
  cols: number
  cells: Array<Array<string>>
  markdown: string
}

/** Parse annexes from an HWP file path */
export declare function parseAnnexHwp(path: string): Array<NapiAnnexInfo>

/** Parse annexes from an HWPX file path */
export declare function parseAnnexHwpx(path: string): Array<NapiAnnexInfo>

/** Parse annex/form markers from Korean legal text */
export declare function parseAnnexText(text: string): Array<NapiAnnexInfo>

/** Parse Korean date expression with today as reference */
export declare function parseDate(text: string): NapiDateResult | null

/** Parse Korean date expression with custom reference date (YYYYMMDD) */
export declare function parseDateWithReference(text: string, referenceDate: string): NapiDateResult | null

/** Extract text and tables from HWP file */
export declare function parseHwpFile(path: string): NapiHwpResult

/** Extract text from HWPX file */
export declare function parseHwpxFile(path: string): string
