//! HWPX generation — Markdown → HWPX (OWPML) writer, document presets, and a
//! container validator. Companion to the read-side [`crate::hwpx`] parser.
//!
//! Ported from kkdoc (MIT): src/hwpx/generator.ts and its sibling modules.
//!
//! # Scope
//! This is a faithful port of the reference's **general** Markdown → HWPX path
//! (headings, paragraphs, bold/italic/code, ordered/unordered nested lists,
//! blockquotes, rules, GFM tables, merged colspan/rowspan HTML tables, image
//! embedding) plus a **bounded preset layer** (7 공문서 presets adjusting
//! margins, body size, line spacing, numbering system, page numbers, and h2
//! markers). The reference's measured decorative assets — gaejosik cover/toc/
//! chapter boxes, 결재란 (approval tables), docframe 두문/결문, and the format
//! profile system — are intentionally out of scope; presets here produce valid,
//! well-styled documents without those measured constants.
//!
//! Equation blocks (`$$ … $$`) render as real `<hp:equation>` elements via
//! [`crate::equation::latex_to_hulk`]; ```chart``` fences render as code blocks
//! for now (marked `TODO(chart)` in `section.rs`).
//!
//! # Example
//! ```
//! use mdm_core::hwpx_gen::{markdown_to_hwpx, validate_hwpx, GenOptions};
//! let bytes = markdown_to_hwpx("# Title\n\nHello **world**.", &GenOptions::default()).unwrap();
//! assert!(validate_hwpx(&bytes).ok);
//! ```

mod blocks;
mod header;
mod ids;
mod image;
mod preset;
mod section;
mod table;
pub mod validate;

use std::io::{Cursor, Write};

use zip::write::SimpleFileOptions;
use zip::CompressionMethod;

pub use ids::HwpxTheme;
pub use preset::Preset;
pub use validate::{validate_hwpx, ValidateIssue, ValidateResult};

/// Options for [`markdown_to_hwpx`].
#[derive(Debug, Clone, Default)]
pub struct GenOptions {
    /// Visual theme (heading/body/quote colors, table header style).
    pub theme: HwpxTheme,
    /// Document preset. `None` = general Markdown mode.
    pub preset: Option<Preset>,
}

impl GenOptions {
    /// Build options for a named preset (Korean or English alias).
    pub fn with_preset(name: &str) -> Self {
        GenOptions {
            theme: HwpxTheme::default(),
            preset: Some(Preset::from_alias(name)),
        }
    }
}

/// Convert Markdown text into an HWPX document (ZIP bytes).
pub fn markdown_to_hwpx(markdown: &str, options: &GenOptions) -> std::io::Result<Vec<u8>> {
    let theme = ids::resolve_theme(&options.theme);
    let resolved = options.preset.map(preset::resolve_preset);
    let resolved_ref = resolved.as_ref();

    let blocks = blocks::parse_markdown_to_blocks(markdown);
    table::reset_table_ids();

    let (header_xml, header_bf) = header::generate_header_xml(&theme, resolved_ref);
    let mut images = image::ImageRegistry::new();
    let section_xml =
        section::blocks_to_section_xml(&blocks, &theme, resolved_ref, header_bf, &mut images);
    let prv_text = blocks::build_prv_text(&blocks);

    let layout = if resolved_ref.is_some() { "gongmun" } else { "default" };
    let manifest = header::generate_manifest(&images.manifest_items(), layout);
    let container = header::generate_container_xml();

    // ── ZIP packaging — mimetype must be the first entry and STORED ──
    let mut cursor = Cursor::new(Vec::new());
    {
        let mut zip = zip::ZipWriter::new(&mut cursor);
        let stored = SimpleFileOptions::default().compression_method(CompressionMethod::Stored);
        let deflated = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);

        zip.start_file("mimetype", stored)?;
        zip.write_all(b"application/hwp+zip")?;

        zip.start_file("META-INF/container.xml", deflated)?;
        zip.write_all(container.as_bytes())?;

        zip.start_file("Contents/content.hpf", deflated)?;
        zip.write_all(manifest.as_bytes())?;

        for part in &images.parts {
            zip.start_file(&part.name, deflated)?;
            zip.write_all(&part.data)?;
        }

        zip.start_file("Contents/header.xml", deflated)?;
        zip.write_all(header_xml.as_bytes())?;

        zip.start_file("Contents/section0.xml", deflated)?;
        zip.write_all(section_xml.as_bytes())?;

        zip.start_file("Preview/PrvText.txt", deflated)?;
        zip.write_all(prv_text.as_bytes())?;

        zip.finish()?;
    }
    Ok(cursor.into_inner())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hwpx::HwpxParser;

    /// Parse generated bytes, returning (joined section text, table info).
    /// Table info is (merged_flag, flattened cell text) to avoid naming the
    /// parser's unexported `Table`/`HwpxDocument` types.
    fn roundtrip(bytes: Vec<u8>) -> (String, Vec<(bool, String)>) {
        let mut p = HwpxParser::from_bytes(bytes).expect("open");
        let doc = p.parse().expect("parse");
        let text = doc.sections.join("\n");
        let tables = doc
            .tables
            .iter()
            .map(|t| {
                let flat = t.cells.iter().flatten().cloned().collect::<Vec<_>>().join("|");
                (t.has_merged_cells(), flat)
            })
            .collect();
        (text, tables)
    }

    #[test]
    fn basic_document_validates() {
        let md = "# 제목\n\n본문 **굵게** 그리고 *기울임*.\n\n- 하나\n- 둘\n";
        let bytes = markdown_to_hwpx(md, &GenOptions::default()).unwrap();
        let res = validate_hwpx(&bytes);
        assert!(res.ok, "issues: {:?}", res.issues);
        assert!(res.entry_count >= 5);
    }

    #[test]
    fn heading_and_paragraph_roundtrip() {
        let md = "# 보고서 제목\n\n첫 문단입니다.\n\n## 소제목\n\n둘째 문단.";
        let bytes = markdown_to_hwpx(md, &GenOptions::default()).unwrap();
        assert!(validate_hwpx(&bytes).ok);
        let (text, _) = roundtrip(bytes);
        assert!(text.contains("보고서 제목"), "text: {text}");
        assert!(text.contains("첫 문단입니다"), "text: {text}");
        assert!(text.contains("소제목"), "text: {text}");
    }

    #[test]
    fn gfm_table_roundtrip() {
        let md = "| 이름 | 값 |\n| --- | --- |\n| 사과 | 100 |\n| 배 | 200 |\n";
        let bytes = markdown_to_hwpx(md, &GenOptions::default()).unwrap();
        assert!(validate_hwpx(&bytes).ok);
        let (_, tables) = roundtrip(bytes);
        assert_eq!(tables.len(), 1, "one table expected");
        let flat = &tables[0].1;
        assert!(flat.contains("이름"), "cells: {flat}");
        assert!(flat.contains("사과"), "cells: {flat}");
        assert!(flat.contains("200"), "cells: {flat}");
    }

    #[test]
    fn merged_html_table_preserves_spans() {
        let md = "<table><tr><th colspan=\"2\">머리</th></tr><tr><td>A</td><td>B</td></tr></table>";
        let bytes = markdown_to_hwpx(md, &GenOptions::default()).unwrap();
        assert!(validate_hwpx(&bytes).ok, "{:?}", validate_hwpx(&bytes).issues);
        let (_, tables) = roundtrip(bytes);
        assert_eq!(tables.len(), 1);
        assert!(tables[0].0, "colspan should survive");
        let flat = &tables[0].1;
        assert!(flat.contains("머리"));
        assert!(flat.contains('A') && flat.contains('B'));
    }

    #[test]
    fn all_seven_presets_generate_valid_hwpx() {
        for name in ["기안문", "보고서", "계획서", "통지", "회의록", "개조식", "보도자료"] {
            let md = "# 문서 제목\n\n## 개요\n\n- 첫째 항목\n- 둘째 항목\n\n본문 내용입니다.";
            let bytes = markdown_to_hwpx(md, &GenOptions::with_preset(name)).unwrap();
            let res = validate_hwpx(&bytes);
            assert!(res.ok, "preset {name} invalid: {:?}", res.issues);
        }
    }

    #[test]
    fn preset_legal_numbering_renders_markers() {
        let md = "- 첫째\n- 둘째\n  - 하위\n";
        let bytes = markdown_to_hwpx(md, &GenOptions::with_preset("기안문")).unwrap();
        assert!(validate_hwpx(&bytes).ok);
        let (text, _) = roundtrip(bytes);
        assert!(text.contains("1."), "expected legal marker: {text}");
    }

    #[test]
    fn embedded_data_uri_image() {
        // 1×1 transparent PNG data URI
        let png = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";
        let md = format!("![alt]({png})");
        let bytes = markdown_to_hwpx(&md, &GenOptions::default()).unwrap();
        let res = validate_hwpx(&bytes);
        assert!(res.ok, "issues: {:?}", res.issues);
        // BinData part embedded
        let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
        let has_bindata = (0..archive.len())
            .any(|i| archive.by_index(i).map(|f| f.name().starts_with("BinData/")).unwrap_or(false));
        assert!(has_bindata, "image bytes should be embedded in BinData/");
    }

    #[test]
    fn equation_block_emits_hp_equation() {
        let md = "본문.\n\n$$ \\frac{a}{b} $$\n\n끝.";
        let bytes = markdown_to_hwpx(md, &GenOptions::default()).unwrap();
        let res = validate_hwpx(&bytes);
        assert!(res.ok, "issues: {:?}", res.issues);
        // section0.xml should contain an <hp:equation> with a script.
        let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes)).unwrap();
        let mut section = String::new();
        {
            use std::io::Read as _;
            let mut f = archive.by_name("Contents/section0.xml").unwrap();
            f.read_to_string(&mut section).unwrap();
        }
        assert!(section.contains("<hp:equation"), "no equation element: {section}");
        assert!(section.contains("<hp:script>"), "no script element");
        assert!(section.contains("over"), "frac should become HULK 'over': {section}");
    }

    #[test]
    fn empty_document_is_valid() {
        let bytes = markdown_to_hwpx("", &GenOptions::default()).unwrap();
        assert!(validate_hwpx(&bytes).ok);
    }

    #[test]
    fn detects_broken_mimetype() {
        // Hand-build a zip whose first entry is not mimetype.
        let mut cursor = std::io::Cursor::new(Vec::new());
        {
            let mut zip = zip::ZipWriter::new(&mut cursor);
            let opt = SimpleFileOptions::default();
            zip.start_file("Contents/header.xml", opt).unwrap();
            zip.write_all(b"<x/>").unwrap();
            zip.finish().unwrap();
        }
        let res = validate_hwpx(&cursor.into_inner());
        assert!(!res.ok);
    }
}
