#!/usr/bin/env python3
"""Extract the HWP3 조합형(Johab) → Unicode lookup table from kkdoc's
reference/kkdoc/src/hwp3/johab-symbols.ts and emit a Rust source file with a
sorted `(u16, u32)` const array for binary search.

Source: reference/kkdoc/src/hwp3/johab-symbols.ts (MIT), itself auto-generated
from rhwp/src/parser/hwp3/johab_map.rs.

Usage:
    python3 scripts/extract_hwp3_johab_table.py \
        reference/kkdoc/src/hwp3/johab-symbols.ts \
        core/src/hwp3/johab_table.rs
"""
import re
import sys

HEX_PAIR_RE = re.compile(r"0x([0-9A-Fa-f]+)\s*,\s*0x([0-9A-Fa-f]+)")

RUST_HEADER = """\
// Auto-generated by scripts/extract_hwp3_johab_table.py — DO NOT EDIT.
// Source: reference/kkdoc/src/hwp3/johab-symbols.ts (MIT), itself ported
// from rhwp/src/parser/hwp3/johab_map.rs.
// Pairs of (johab-code, unicode-codepoint), sorted by key for binary search.
// Total entries: {count}

/// (johab hchar code, unicode codepoint) pairs, sorted ascending by key.
pub static JOHAB_SYMBOLS: &[(u16, u32)] = &[
{body}
];
"""


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    src_path, dst_path = sys.argv[1], sys.argv[2]

    with open(src_path, "r", encoding="utf-8") as f:
        src = f.read()

    pairs = [(int(k, 16), int(v, 16)) for k, v in HEX_PAIR_RE.findall(src)]
    if not pairs:
        raise SystemExit("no pairs extracted — regex or source format mismatch")

    # Sanity: source claims a specific count in its header comment.
    m = re.search(r"Total entries:\s*(\d+)", src)
    if m and int(m.group(1)) != len(pairs):
        raise SystemExit(
            f"extracted {len(pairs)} pairs but source header claims {m.group(1)}"
        )

    pairs.sort(key=lambda p: p[0])

    lines = []
    row = []
    for k, v in pairs:
        row.append(f"    (0x{k:04X}, 0x{v:04X}),")
        if len(row) == 4:
            lines.append(" ".join(row))
            row = []
    if row:
        lines.append(" ".join(row))

    out = RUST_HEADER.format(count=len(pairs), body="\n".join(lines))
    with open(dst_path, "w", encoding="utf-8") as f:
        f.write(out)

    print(f"wrote {len(pairs)} entries to {dst_path}")


if __name__ == "__main__":
    main()
